/*
 * rlcrackzip - Zip password cracker.
 *
 * Copyright (C) 2012 Ryan Lothian and Marc Lehmann (see AUTHORS file).
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
 */

#ifndef ZIP_CRACK_H
#define ZIP_CRACK_H

#include <stdint.h>
#include <iostream>
#include "crc32.h"
#include "zip_read.h"
#include "generators.h"


class PasswordCollectorInterface
{
public:
    virtual void collect(const StaticVector<char, MAX_PW_LEN>  password) = 0;
};


/* Just print to stdout */
class PasswordCollectorPrint : public PasswordCollectorInterface
{
public:
    virtual void collect(const StaticVector<char, MAX_PW_LEN> password) {
        #pragma omp critical
        {
            for (uint32_t i = 0;  i < password.size(); i++) {
                std::cout << password[i];
            }
            std::cout << "\n";
        }
    }
};


class DecodeCheckerInterface
{
public:
    /*
     * Returns true iff the 12 decoded bytes look reasonable, i.e. if it the password MAY be correct.
     */
    virtual bool check(const file_info_type&          file,
                       const StaticVector<uint8_t, FILE_READ_SIZE>&  decode) const = 0;
};


class DecodeChecker : public DecodeCheckerInterface
{
private:
    StaticVector<bool, 65536> is_quadratic_residue;

public:
    DecodeChecker(bool check_quadratic_residues=false);
    bool check(const file_info_type&             file,
               const StaticVector<uint8_t, FILE_READ_SIZE>&  decode) const;
    float false_positive_rate() const;
};


/*
 * This function examines candidate passwords generated by generator_fn and rules out most of them
 * using knowledge of zip file structure.
 */
void
crack_zip_password (const std::vector<file_info_type>  &files,
                    GeneratorInterface               &generator,
                    DecodeCheckerInterface           &checker,
                    PasswordCollectorInterface       &collector);



/*
 * Implements the standard zip encryption stream cipher.
 *
 * Note: the encryption provided is weak and should not be used to store sensitive data.
 */
class ZipStreamCipher
{
private:
    /*
     * The stream cipher has 96-bits of state.
     */
    uint32_t  key[3];

    /*
     * Prevent implicit instantiation.
     */
    ZipStreamCipher () {}

public:


    /*
     * Standard starting state for the zip cipher
     */
    static ZipStreamCipher initialState();

    /*
     * Advance stream cipher state by one byte. Note that the next state depends on the most
     * recent plaintext (or password) character.
     */
    void advanceOneByte(uint8_t  pw_char);

    /*
     * Convert state to a byte that can be xored with plaintext to get ciphertext (or vice-versa of course).
     */
    uint8_t getKeystreamByte() const;

    /*
     * Print state.
     */
    friend std::ostream& operator<<(std::ostream& output, const ZipStreamCipher&  zsc);
};


#endif /* ZIP_CRACK_H */
